AWSTemplateFormatVersion: "2010-09-09"

Description: "Ejemplo de creacion de una cola con una lambda y bucket de S3"

Resources:
  # Cola SQS
  RegistersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "UdeMRegistersQueue"

  # Bucket Registros Eventos
  RegistersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "udem-events-lambda-registers"

  # Rol Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17" # La versión del documento de política
        Statement:
          - Effect: "Allow" # Permite la acción descrita
            Principal:
              Service: "lambda.amazonaws.com" # El servicio que asume este rol, en este caso Lambda
            Action: "sts:AssumeRole" # Acción que permite a Lambda asumir este rol

      # Aquí definimos las políticas que se adjuntarán al rol, otorgando permisos específicos a Lambda
      Policies:
        - PolicyName: "LambdaBasicExecution" # Nombre de la política personalizada
          PolicyDocument:
            Version: "2012-10-17" # La versión del documento de política
            Statement:
              - Effect: "Allow" # Permite la acción descrita
                Action:
                  - "logs:CreateLogGroup" # Permite la creación de un grupo de logs en CloudWatch
                  - "logs:CreateLogStream" # Permite la creación de un stream de logs en CloudWatch
                  - "logs:PutLogEvents" # Permite escribir eventos de logs en CloudWatch
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: "*" # Aplica los permisos a todos los recursos (en este caso, a todos los grupos y streams de logs)
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                Resource: !Sub "${RegistersBucket.Arn}/*"

  # Politica Bucket Registros Eventos
  RegistersBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RegistersBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !GetAtt LambdaExecutionRole.Arn # Referencia al ARN del rol Lambda
            Action:
              - "s3:PutObject"
            Resource: !Sub "${RegistersBucket.Arn}/*"

  # Politica Bucket codigo lambda
  LambdaCodeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: udem-lambda-code
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
              AWS: !GetAtt LambdaExecutionRole.Arn # Referencia al ARN del rol Lambda
            Resource: "arn:aws:s3:::udem-lambda-code/*" # Ruta a los objetos en S3

  RegistersQueueLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "UdeMRegistersQueueLambda"
      Handler: lambda_function_registers.lambda_handler # Nombre del archivo y la función handler en Python
      Runtime: python3.11
      Environment:
        Variables:
          QUEUE_URL: !GetAtt RegistersQueue.QueueUrl
          REGISTERS_BUCKET: !Ref RegistersBucket
      Code:
        S3Bucket: udem-lambda-code # Referencia al bucket creado en CloudFormation
        S3Key: lambda_function_registers.zip # Archivo zip subido a S3 que contiene el código
      MemorySize: 128 # Memoria personalizada para la Lambda (en MB)
      Timeout: 25 # Timeout personalizado de 25 segundos
      Role: !GetAtt LambdaExecutionRole.Arn # Role que la función Lambda asumirá

  # Asociar la cola SQS como trigger para la función Lambda
  LambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt RegistersQueue.Arn
      FunctionName: !Ref RegistersQueueLambda
      Enabled: True

Outputs:
  LambdaFunctionName:
    Description: "Nombre de la función Lambda desplegada"
    Value: !Ref RegistersQueueLambda # Output que muestra el nombre de la función Lambda
